[pytest]
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:Warning
    ignore:numpy.core is deprecated and has been renamed to numpy._core.*:DeprecationWarning
    ignore:Call to deprecated function 'Dependency'.*:Warning
    ignore:Use of deprecated class 'DependencyKwarg'.*:Warning
